import type { SalesOrder, Shipment, WarehouseTransfer } from '../types/operations'

export const SAMPLE_WAREHOUSES = [
  'Central Hub - Building A (Dallas)',
  'North Logistics Depot (Chicago)',
  'West Coast Fulfillment (Oakland)',
  'East Coast Distribution (Newark)',
  'Southern Express Facility (Atlanta)',
]

export const SAMPLE_PRODUCTS = [
  { name: 'Ergonomic Desk Chair Pro', sku: 'SKU-EDC-01', defaultPrice: 249.99 },
  { name: 'Mechanical Keypad Matrix 87', sku: 'SKU-MKM-02', defaultPrice: 89.5 },
  { name: 'Ultrawide 34" Curved Monitor', sku: 'SKU-UCM-03', defaultPrice: 429.0 },
  { name: 'Heavy-Duty Steel Storage Rack', sku: 'SKU-SSR-04', defaultPrice: 175.0 },
  { name: 'Wireless Barcode Scanner BT5', sku: 'SKU-WBS-05', defaultPrice: 119.99 },
  { name: 'Direct Thermal Shipping Labels (5000pk)', sku: 'SKU-TSL-06', defaultPrice: 45.0 },
  { name: 'Industrial HEPA Air Purifier X9', sku: 'SKU-HAP-07', defaultPrice: 310.0 },
]

export const INITIAL_SALES_ORDERS: SalesOrder[] = [
  {
    id: 'SO-2026-001',
    customer: 'Apex Retailers Inc.',
    customerEmail: 'procurement@apexretail.com',
    customerType: 'Retailer',
    orderDate: '2026-09-22',
    status: 'Packed',
    totalAmount: 18740.0,
    notes: 'Priority dock dispatch requested for flagship store restocking.',
    items: [
      {
        productId: 'prod-1',
        productName: 'Ergonomic Desk Chair Pro',
        sku: 'SKU-EDC-01',
        quantity: 40,
        unitPrice: 249.99,
      },
      {
        productId: 'prod-2',
        productName: 'Mechanical Keypad Matrix 87',
        sku: 'SKU-MKM-02',
        quantity: 60,
        unitPrice: 89.5,
      },
      {
        productId: 'prod-5',
        productName: 'Wireless Barcode Scanner BT5',
        sku: 'SKU-WBS-05',
        quantity: 30,
        unitPrice: 112.0,
      },
    ],
    auditLogs: [
      {
        status: 'Placed',
        timestamp: '2026-09-22 09:30 AM',
        updatedBy: 'Self-Service Portal (EDI)',
        note: 'Order submitted with standard terms',
      },
      {
        status: 'Confirmed',
        timestamp: '2026-09-22 11:15 AM',
        updatedBy: 'Claire Dunphy (Account Exec)',
        note: 'Credit line verified and approved',
      },
      {
        status: 'Processing',
        timestamp: '2026-09-23 08:45 AM',
        updatedBy: 'Marcus Vance (Warehouse Lead)',
        note: 'Pick ticket batch #104 allocated',
      },
      {
        status: 'Packed',
        timestamp: '2026-09-24 03:20 PM',
        updatedBy: 'David Kim (Packing Team B)',
        note: 'Palletized onto 2 wrap-sealed skids',
      },
    ],
  },
  {
    id: 'SO-2026-002',
    customer: 'Metro Electronics Mart',
    customerEmail: 'orders@metroelectronic.net',
    customerType: 'Distributor',
    orderDate: '2026-09-23',
    status: 'Processing',
    totalAmount: 12870.0,
    notes: 'Fragile handling required on monitor packaging.',
    items: [
      {
        productId: 'prod-3',
        productName: 'Ultrawide 34" Curved Monitor',
        sku: 'SKU-UCM-03',
        quantity: 30,
        unitPrice: 429.0,
      },
    ],
    auditLogs: [
      {
        status: 'Placed',
        timestamp: '2026-09-23 10:05 AM',
        updatedBy: 'API Partner Webhook',
      },
      {
        status: 'Confirmed',
        timestamp: '2026-09-23 01:20 PM',
        updatedBy: 'Claire Dunphy (Account Exec)',
      },
      {
        status: 'Processing',
        timestamp: '2026-09-24 09:10 AM',
        updatedBy: 'Marcus Vance (Warehouse Lead)',
        note: 'Goods staging at Zone B-14',
      },
    ],
  },
  {
    id: 'SO-2026-003',
    customer: 'Summit Outfitter Co.',
    customerEmail: 'supply@summitoutfitter.com',
    customerType: 'Retailer',
    orderDate: '2026-09-25',
    status: 'Confirmed',
    totalAmount: 7600.0,
    notes: 'Seasonal replenishment for Midwest stores.',
    items: [
      {
        productId: 'prod-4',
        productName: 'Heavy-Duty Steel Storage Rack',
        sku: 'SKU-SSR-04',
        quantity: 20,
        unitPrice: 175.0,
      },
      {
        productId: 'prod-7',
        productName: 'Industrial HEPA Air Purifier X9',
        sku: 'SKU-HAP-07',
        quantity: 10,
        unitPrice: 310.0,
      },
      {
        productId: 'prod-6',
        productName: 'Direct Thermal Shipping Labels (5000pk)',
        sku: 'SKU-TSL-06',
        quantity: 22,
        unitPrice: 45.0,
      },
    ],
    auditLogs: [
      {
        status: 'Placed',
        timestamp: '2026-09-25 08:15 AM',
        updatedBy: 'Retail Portal',
      },
      {
        status: 'Confirmed',
        timestamp: '2026-09-25 11:30 AM',
        updatedBy: 'Alex Chen (Order Desk)',
        note: 'Inventory inventory hold established',
      },
    ],
  },
  {
    id: 'SO-2026-004',
    customer: 'Vanguard Workspace Systems',
    customerEmail: 'b2b@vanguardws.io',
    customerType: 'Corporate',
    orderDate: '2026-09-26',
    status: 'Placed',
    totalAmount: 4999.8,
    notes: 'New client trial bulk purchase.',
    items: [
      {
        productId: 'prod-1',
        productName: 'Ergonomic Desk Chair Pro',
        sku: 'SKU-EDC-01',
        quantity: 20,
        unitPrice: 249.99,
      },
    ],
    auditLogs: [
      {
        status: 'Placed',
        timestamp: '2026-09-26 09:45 AM',
        updatedBy: 'Direct Sales Rep',
        note: 'Initial order placement',
      },
    ],
  },
]

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: 'SHP-8841',
    orderId: 'SO-2026-001',
    customer: 'Apex Retailers Inc.',
    destination: '742 Commerce Blvd, Distribution Dock 4, Chicago, IL 60607',
    carrier: 'FedEx Freight Logistics',
    trackingNumber: 'FXF-9402-88192-US',
    status: 'Out for Delivery',
    createdDate: '2026-09-24',
    estimatedDelivery: '2026-09-26 by 5:00 PM',
    items: [
      { productName: 'Ergonomic Desk Chair Pro', sku: 'SKU-EDC-01', quantity: 40 },
      { productName: 'Mechanical Keypad Matrix 87', sku: 'SKU-MKM-02', quantity: 60 },
      { productName: 'Wireless Barcode Scanner BT5', sku: 'SKU-WBS-05', quantity: 30 },
    ],
    timeline: [
      {
        key: 'Shipped',
        label: 'Shipped',
        timestamp: '2026-09-24 04:30 PM',
        user: 'Marcus Vance (Dispatch Lead)',
        description: 'Loaded onto outbound line-haul trailer #T-489.',
      },
      {
        key: 'Out for Delivery',
        label: 'Out for Delivery',
        timestamp: '2026-09-26 07:45 AM',
        user: 'James O\'Connor (Regional Driver)',
        description: 'Loaded onto local step-van delivery route.',
      },
      {
        key: 'Delivered',
        label: 'Delivered',
        timestamp: null,
        user: null,
        description: 'Destination dock sign-off pending.',
      },
    ],
  },
  {
    id: 'SHP-8842',
    orderId: 'SO-2025-994',
    customer: 'Horizon Tech Supplies',
    destination: '1200 Innovation Way, Building 2, Austin, TX 78701',
    carrier: 'Swift Express Ground',
    trackingNumber: 'SWF-7721-00441-TX',
    status: 'Delivered',
    createdDate: '2026-09-21',
    estimatedDelivery: '2026-09-23 by 1:00 PM',
    items: [
      { productName: 'Wireless Barcode Scanner BT5', sku: 'SKU-WBS-05', quantity: 50 },
      { productName: 'Direct Thermal Shipping Labels (5000pk)', sku: 'SKU-TSL-06', quantity: 15 },
    ],
    timeline: [
      {
        key: 'Shipped',
        label: 'Shipped',
        timestamp: '2026-09-21 02:00 PM',
        user: 'Elena Rostova (Fulfillment)',
        description: 'Handed off to Swift Express courier.',
      },
      {
        key: 'Out for Delivery',
        label: 'Out for Delivery',
        timestamp: '2026-09-23 08:30 AM',
        user: 'Swift Express Austin Team',
        description: 'Out on delivery courier van #12.',
      },
      {
        key: 'Delivered',
        label: 'Delivered',
        timestamp: '2026-09-23 12:45 PM',
        user: 'Robert Ramos (Dock Supervisor - Receiver)',
        description: 'Signed for at Loading Bay 3.',
      },
    ],
  },
  {
    id: 'SHP-8843',
    orderId: 'SO-2026-002',
    customer: 'Metro Electronics Mart',
    destination: '890 Northern Parkway, Bay 11, Minneapolis, MN 55401',
    carrier: 'DHL Global Forwarding',
    trackingNumber: 'DHL-3382-99104-US',
    status: 'Shipped',
    createdDate: '2026-09-25',
    estimatedDelivery: '2026-09-28 by 3:00 PM',
    items: [
      { productName: 'Ultrawide 34" Curved Monitor', sku: 'SKU-UCM-03', quantity: 30 },
    ],
    timeline: [
      {
        key: 'Shipped',
        label: 'Shipped',
        timestamp: '2026-09-25 05:15 PM',
        user: 'Sarah Jenkins (Outbound Ops)',
        description: 'Dispatched from Central Hub Dallas.',
      },
      {
        key: 'Out for Delivery',
        label: 'Out for Delivery',
        timestamp: null,
        user: null,
        description: 'En route between regional sorting nodes.',
      },
      {
        key: 'Delivered',
        label: 'Delivered',
        timestamp: null,
        user: null,
        description: 'Awaiting local delivery completion.',
      },
    ],
  },
]

export const INITIAL_TRANSFERS: WarehouseTransfer[] = [
  {
    id: 'TRF-3001',
    sourceWarehouse: 'Central Hub - Building A (Dallas)',
    destinationWarehouse: 'North Logistics Depot (Chicago)',
    product: 'Ergonomic Desk Chair Pro',
    sku: 'SKU-EDC-01',
    quantity: 65,
    notes: 'Urgent stock balancing for Chicago enterprise order fulfillment.',
    priority: 'Urgent',
    status: 'In Transit',
    createdAt: '2026-09-24 10:30 AM',
    timeline: [
      {
        key: 'Created',
        label: 'Created',
        timestamp: '2026-09-24 10:30 AM',
        user: 'Sarah Jenkins (Inventory Analyst)',
        description: 'Transfer order initiated from reorder threshold alert.',
      },
      {
        key: 'Accepted',
        label: 'Accepted',
        timestamp: '2026-09-24 01:15 PM',
        user: 'Marcus Vance (Central Warehouse Mgr)',
        description: 'Inventory picked and verified at Central Hub.',
      },
      {
        key: 'In Transit',
        label: 'In Transit',
        timestamp: '2026-09-25 06:00 AM',
        user: 'David Park (Logistics Carrier Lead)',
        description: 'Departed Dallas on inter-depot truck #42.',
      },
      {
        key: 'Received',
        label: 'Received',
        timestamp: null,
        user: null,
        description: 'Awaiting intake scanning at North Logistics Depot.',
      },
    ],
  },
  {
    id: 'TRF-3002',
    sourceWarehouse: 'West Coast Fulfillment (Oakland)',
    destinationWarehouse: 'East Coast Distribution (Newark)',
    product: 'Mechanical Keypad Matrix 87',
    sku: 'SKU-MKM-02',
    quantity: 120,
    notes: 'Q4 regional buffer redistribution.',
    priority: 'Standard',
    status: 'Accepted',
    createdAt: '2026-09-25 02:45 PM',
    timeline: [
      {
        key: 'Created',
        label: 'Created',
        timestamp: '2026-09-25 02:45 PM',
        user: 'Alex Chen (Supply Planner)',
        description: 'System-generated reallocation request.',
      },
      {
        key: 'Accepted',
        label: 'Accepted',
        timestamp: '2026-09-26 09:00 AM',
        user: 'Elena Rostova (West Coast Mgr)',
        description: 'Stock staged for scheduled cross-country freight.',
      },
      {
        key: 'In Transit',
        label: 'In Transit',
        timestamp: null,
        user: null,
        description: 'Awaiting freight carrier pickup.',
      },
      {
        key: 'Received',
        label: 'Received',
        timestamp: null,
        user: null,
        description: 'Pending arrival and inspection.',
      },
    ],
  },
  {
    id: 'TRF-3003',
    sourceWarehouse: 'Southern Express Facility (Atlanta)',
    destinationWarehouse: 'Central Hub - Building A (Dallas)',
    product: 'Direct Thermal Shipping Labels (5000pk)',
    sku: 'SKU-TSL-06',
    quantity: 250,
    notes: 'Consumable packaging supplies transfer.',
    priority: 'Standard',
    status: 'Received',
    createdAt: '2026-09-20 08:00 AM',
    timeline: [
      {
        key: 'Created',
        label: 'Created',
        timestamp: '2026-09-20 08:00 AM',
        user: 'Tom Bradley (Procurement)',
        description: 'Transfer request logged for packaging materials.',
      },
      {
        key: 'Accepted',
        label: 'Accepted',
        timestamp: '2026-09-20 11:30 AM',
        user: 'Atlanta Ops Dispatch',
        description: 'Palletized for transit.',
      },
      {
        key: 'In Transit',
        label: 'In Transit',
        timestamp: '2026-09-21 07:00 AM',
        user: 'Interstate Transport LLC',
        description: 'Linehaul freight in transit.',
      },
      {
        key: 'Received',
        label: 'Received',
        timestamp: '2026-09-22 03:40 PM',
        user: 'Rachel Kim (Receiving Lead - Dallas)',
        description: 'Inspected, counted, and shelved in Zone A.',
      },
    ],
  },
  {
    id: 'TRF-3004',
    sourceWarehouse: 'Central Hub - Building A (Dallas)',
    destinationWarehouse: 'Southern Express Facility (Atlanta)',
    product: 'Ultrawide 34" Curved Monitor',
    sku: 'SKU-UCM-03',
    quantity: 15,
    notes: 'Customer showroom requirement in Atlanta.',
    priority: 'Standard',
    status: 'Created',
    createdAt: '2026-09-26 11:20 AM',
    timeline: [
      {
        key: 'Created',
        label: 'Created',
        timestamp: '2026-09-26 11:20 AM',
        user: 'Alex Chen (Order Desk)',
        description: 'Draft transfer requested by regional account manager.',
      },
      {
        key: 'Accepted',
        label: 'Accepted',
        timestamp: null,
        user: null,
        description: 'Pending source warehouse supervisor approval.',
      },
      {
        key: 'In Transit',
        label: 'In Transit',
        timestamp: null,
        user: null,
        description: 'Pending carrier dispatch.',
      },
      {
        key: 'Received',
        label: 'Received',
        timestamp: null,
        user: null,
        description: 'Pending delivery.',
      },
    ],
  },
]
